# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rack', '= 3.0.0'
gem 'rackup'
gem 'inner_html_content', :git => 'https://github.com/xiosky90/ruby_inner_html_content.git', :branch => 'main'
# gem "byebug", "~> 11.1", :groups => [:development, :test] 
