---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/articles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show article
      tags:
      - Articles
      parameters:
      - name: status
        in: query
        schema:
          type: string
          enum:
          - unpublished
          - published
        description: 'Get comments with status: published/unpublished.'
      - name: last
        in: query
        description: 'Get last limit comments with limit: integer.'
        schema:
          type: integer
      responses:
        '200':
          description: successful
    patch:
      summary: update article
      tags:
      - Articles
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                  enum:
                  - unpublished
                  - published
                author_id:
                  type: integer
              required: false
    put:
      summary: update article
      tags:
      - Articles
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                  enum:
                  - unpublished
                  - published
                author_id:
                  type: integer
              required: false
    delete:
      summary: delete article
      tags:
      - Articles
      responses:
        '204':
          description: successful
  "/api/v1/comments/published":
    get:
      summary: published comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
  "/api/v1/comments/unpublished":
    get:
      summary: unpublished comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
  "/api/v1/comments":
    get:
      summary: list comments
      tags:
      - Comments
      parameters:
      - name: status
        in: query
        schema:
          type: string
          enum:
          - unpublished
          - published
        description: 'Get comments with status: published/unpublished.'
      - name: last
        in: query
        description: 'Get last limit comments with limit: integer.'
        schema:
          type: integer
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      tags:
      - Comments
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                author_id:
                  type: integer
                article_id:
                  type: integer
              required:
              - body
              - author_id
              - article_id
        description: status key is default value = unpublished
  "/api/v1/comments/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
    patch:
      summary: update comment
      tags:
      - Comments
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                  enum:
                  - unpublished
                  - published
                author_id:
                  type: integer
                articler_id:
                  type: integer
              required: false
    put:
      summary: update comment
      tags:
      - Comments
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                  enum:
                  - unpublished
                  - published
                author_id:
                  type: integer
                articler_id:
                  type: integer
              required: false
    delete:
      summary: delete comment
      tags:
      - Comments
      responses:
        '204':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
